# These are supported funding model platforms

github: [otitoju]
patreon: otitoju
open_collective: robust-email-validator
ko_fi: otitoju
tidelift: npm/robust-email-validator
community_bridge: robust-email-validator
liberapay: otitoju
issuehunt: otitoju
otechie: otitoju
lfx_crowdfunding: robust-email-validator
custom: ['https://paypal.me/otitoju', 'https://buymeacoffee.com/otitoju']
